# Generated by Django 5.2.4 on 2025-08-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
